use std::sync::Arc;

use actix_web::{HttpRequest, HttpResponse, web, cookie::Cookie, http::header};
use crate::auth::confs::JwtAuthConf;
use crate::auth::traits::SessionStore;
use crate::auth_oauth2::models::{
    OAuth2CallbackRequest, OAuth2LoginQuery, OAuth2LoginResponse,
};
use crate::auth_oauth2::services::OAuth2Service;
use crate::auth_oauth2::traits::{OAuth2Identity, OAuth2SessionStore, OAuth2UserHandler};
use crate::core::models::CornettiResult;

/// Builds a route handler for OAuth2 web login (redirect to provider).
///
/// GET /auth/oauth2/{provider}/login[?code_challenge=...]
///
/// Stores the CSRF state in a cookie for callback verification and responds
/// with a `302` to the provider.
///
/// The `code_challenge` is optional: when absent, PKCE is server-generated,
/// which is adequate for the web flow because the `HttpOnly` cookie still
/// binds the flow to the browser that started it. For the mobile flow use
/// [`oauth2_api_login_handler`], which requires it.
///
/// # Security
///
/// Unauthenticated endpoint that writes an entry to the store on every call:
/// should be protected by rate limiting at the application level.
pub async fn oauth2_login_handler<U, T, St>(
    service: web::Data<Arc<OAuth2Service<U, T, St>>>,
    path: web::Path<String>,
    query: web::Query<OAuth2LoginQuery>,
) -> CornettiResult<HttpResponse>
where
    U: OAuth2UserHandler<T>,
    T: Clone,
    St: OAuth2SessionStore + 'static,
{
    let provider_name = path.into_inner();
    let (auth_url, state) = service
        .build_auth_url(&provider_name, query.code_challenge.as_deref())
        .await?;

    let state_cookie = Cookie::build(&service.conf().state_cookie_name, state)
        .path("/")
        .http_only(true)
        .secure(true)
        .same_site(actix_web::cookie::SameSite::Lax)
        .finish();

    Ok(HttpResponse::Found()
        .cookie(state_cookie)
        .insert_header((header::LOCATION, auth_url))
        .finish())
}

/// Builds a route handler for OAuth2 login in API/mobile mode.
///
/// GET /auth/oauth2/{provider}/authorize?code_challenge=...
///
/// Responds `200` with JSON `{ auth_url, state }` instead of a redirect: the
/// client opens `auth_url` and returns `state` in the callback. Does not set
/// cookies.
///
/// Requires `enable_api_mode` enabled in configuration.
///
/// # Security
///
/// `code_challenge` is **mandatory**. Without client-side PKCE, anyone
/// intercepting the provider's redirect (e.g. an app registered on the same
/// custom URI scheme) would get both `code` and `state`, enough to complete
/// the exchange and obtain the victim's tokens.
pub async fn oauth2_api_login_handler<U, T, St>(
    service: web::Data<Arc<OAuth2Service<U, T, St>>>,
    path: web::Path<String>,
    query: web::Query<OAuth2LoginQuery>,
) -> CornettiResult<HttpResponse>
where
    U: OAuth2UserHandler<T>,
    T: Clone,
    St: OAuth2SessionStore + 'static,
{
    if !service.conf().enable_api_mode {
        return Err(crate::errors::auth_oauth2_errors::api_mode_disabled()
            .with_internal_detail("OAuth2 API mode disabled by configuration"));
    }

    let code_challenge = query.code_challenge.as_deref().ok_or_else(|| {
        crate::errors::auth_oauth2_errors::invalid_pkce_parameter().with_internal_detail(
            "code_challenge is mandatory in API mode: PKCE must be \
             generated by the client",
        )
    })?;

    let provider_name = path.into_inner();
    let (auth_url, state) = service
        .build_auth_url(&provider_name, Some(code_challenge))
        .await?;

    Ok(HttpResponse::Ok().json(OAuth2LoginResponse { auth_url, state }))
}

/// Builds the callback route in WEB mode.
///
/// GET /auth/oauth2/{provider}/callback?code=...&state=...
///
/// Verifies the state from the cookie, exchanges the code, looks up/creates
/// the user, issues JWT (access + refresh token), sets cookies and redirects.
///
/// Requires `jwt_search_in_cookies` enabled: tokens are delivered exclusively
/// via cookies, so without that flag the redirect would happen without
/// credentials. Use
/// [`OAuth2AuthConf::validate_web_mode`](crate::auth_oauth2::confs::OAuth2AuthConf::validate_web_mode)
/// at startup to catch this before the first login.
pub async fn oauth2_web_callback_handler<U, T, S, St>(
    service: web::Data<Arc<OAuth2Service<U, T, St>>>,
    jwt_conf: web::Data<Arc<JwtAuthConf>>,
    session_store: web::Data<Option<Arc<S>>>,
    tenant_id: web::Data<String>,
    path: web::Path<String>,
    query: web::Query<std::collections::HashMap<String, String>>,
    req: HttpRequest,
) -> CornettiResult<HttpResponse>
where
    U: OAuth2UserHandler<T> + Send + Sync + 'static,
    T: Clone + OAuth2Identity + serde::Serialize + 'static,
    S: SessionStore + 'static,
    St: OAuth2SessionStore + 'static,
{
    if !jwt_conf.jwt_search_in_cookies {
        return Err(
            crate::errors::auth_oauth2_errors::web_mode_misconfigured().with_internal_detail(
                "Il callback web OAuth2 consegna i token via cookie: \
                 impostare jwt_search_in_cookies = true in [auth.jwt]",
            ),
        );
    }

    let provider_name = path.into_inner();

    let code = query
        .get("code")
        .cloned()
        .ok_or_else(crate::errors::auth_oauth2_errors::missing_code)?;

    let state = query
        .get("state")
        .cloned()
        .unwrap_or_default();

    let expected_state = req
        .cookie(&service.conf().state_cookie_name)
        .map(|c| c.value().to_string())
        .unwrap_or_default();

    // Il flusso web usa sempre PKCE lato server: nessun verifier dal client.
    let (user, _metadata) = service
        .handle_callback(&provider_name, code, state, Some(&expected_state), None)
        .await?;

    let identity = user.subject();

    let (_login_response, access_cookie, refresh_cookie, csrf_access, csrf_refresh) =
        crate::actix::auth::helpers::generate_auth_tokens_and_response(
            &jwt_conf,
            user,
            identity,
            &tenant_id,
            req,
            session_store.get_ref().clone(),
        )
        .await?;

    let redirect_url = service
        .conf()
        .post_login_redirect
        .clone()
        .unwrap_or_else(|| "/".to_string());

    let mut response = HttpResponse::Found();
    response.insert_header((header::LOCATION, redirect_url));

    if let Some(c) = access_cookie {
        response.cookie(c);
    }
    if let Some(c) = refresh_cookie {
        response.cookie(c);
    }
    if let Some(c) = csrf_access {
        response.cookie(c);
    }
    if let Some(c) = csrf_refresh {
        response.cookie(c);
    }

    // Rimuovi il cookie di state
    let mut removal = Cookie::build(&service.conf().state_cookie_name, "")
        .path("/")
        .http_only(true)
        .secure(true)
        .same_site(actix_web::cookie::SameSite::Lax)
        .max_age(actix_web::cookie::time::Duration::seconds(0))
        .finish();
    removal.make_removal();
    response.cookie(removal);

    Ok(response.finish())
}

/// Builds the callback route in API/mobile mode.
///
/// POST /auth/oauth2/{provider}/token
/// Body JSON: { "code": "...", "state": "...", "code_verifier": "..." }
///
/// Returns JSON with access_token, refresh_token, expires_in, identity.
/// Does not set cookies — suitable for mobile apps.
///
/// State verification happens through the `OAuth2SessionStore` (one-shot)
/// inside `handle_callback`: an unknown or reused state fails with
/// `pkce_not_found`.
///
/// Requires `enable_api_mode` enabled in configuration.
///
/// # Security
///
/// `code_verifier` is mandatory because the flow is started by
/// [`oauth2_api_login_handler`], which enforces client-side PKCE. A callback
/// without a verifier fails with `pkce_mode_mismatch`.
pub async fn oauth2_api_callback_handler<U, T, S, St>(
    service: web::Data<Arc<OAuth2Service<U, T, St>>>,
    jwt_conf: web::Data<Arc<JwtAuthConf>>,
    session_store: web::Data<Option<Arc<S>>>,
    tenant_id: web::Data<String>,
    path: web::Path<String>,
    body: web::Json<OAuth2CallbackRequest>,
    req: HttpRequest,
) -> CornettiResult<HttpResponse>
where
    U: OAuth2UserHandler<T> + Send + Sync + 'static,
    T: Clone + OAuth2Identity + serde::Serialize + 'static,
    S: SessionStore + 'static,
    St: OAuth2SessionStore + 'static,
{
    if !service.conf().enable_api_mode {
        return Err(crate::errors::auth_oauth2_errors::api_mode_disabled()
            .with_internal_detail("OAuth2 API mode disabled by configuration"));
    }

    let provider_name = path.into_inner();

    let (user, _metadata) = service
        .handle_callback(
            &provider_name,
            body.code.clone(),
            body.state.clone(),
            None,
            body.code_verifier.clone(),
        )
        .await?;

    let identity = user.subject();

    let (login_response, _, _, _, _) =
        crate::actix::auth::helpers::generate_auth_tokens_and_response(
            &jwt_conf,
            user,
            identity,
            &tenant_id,
            req,
            session_store.get_ref().clone(),
        )
        .await?;

    Ok(HttpResponse::Ok().json(login_response))
}
