use crate::statics::models::EnumValue;

const TIPO_STRUMENTAZIONE: &[EnumValue] = &[
    EnumValue { name: "Telescopio", value: "telescopio" },
    EnumValue { name: "Barlow/Correttore", value: "barlow_correttore" },
    EnumValue { name: "Torretta", value: "torretta" },
    EnumValue { name: "Binocolo", value: "binocolo" },
    EnumValue { name: "Oculare", value: "oculare" },
    EnumValue { name: "Cercatore", value: "cercatore" },
    EnumValue { name: "Altro", value: "altro" },
];

const TIPO_OGGETTO: &[EnumValue] = &[
    EnumValue { name: "Galassia", value: "GAL" },
    EnumValue { name: "Galassia Ellittica", value: "GAL_EL" },
    EnumValue { name: "Galassia Lenticolare", value: "GAL_LN" },
    EnumValue { name: "Galassia Spirale", value: "GAL_SP" },
    EnumValue { name: "Galassia Barrata", value: "GAL_SB" },
    EnumValue { name: "Galassia Irregolare", value: "GAL_IR" },
    EnumValue { name: "Galassia Nana", value: "GAL_DW" },
    EnumValue { name: "Galassia Peculiare", value: "GAL_PEC" },
    EnumValue { name: "Galassia Attiva", value: "GAL_AGN" },
    EnumValue { name: "Ammasso Aperto", value: "OpC" },
    EnumValue { name: "Ammasso Globulare", value: "GCl" },
    EnumValue { name: "Nebulosa", value: "Neb" },
    EnumValue { name: "Nebulosa a Emissione", value: "EmN" },
    EnumValue { name: "Nebulosa a Riflessione", value: "RfN" },
    EnumValue { name: "Nebulosa Planetaria", value: "PN" },
    EnumValue { name: "Resto di Supernova", value: "SNR" },
    EnumValue { name: "Regione HII", value: "HII" },
    EnumValue { name: "Nebulosa Oscura", value: "DkNeb" },
    EnumValue { name: "Ammasso di Galassie", value: "GCL" },
    EnumValue { name: "Gruppo di Galassie", value: "HCG" },
    EnumValue { name: "Stella", value: "Star" },
    EnumValue { name: "Stella Doppia", value: "2Star" },
    EnumValue { name: "Asterismo", value: "Aster" },
    EnumValue { name: "Nube Stellare", value: "StarCloud" },
    EnumValue { name: "Nebulosa + Ammasso", value: "Neb+OpC" },
    EnumValue { name: "Quasar", value: "QSO" },
    EnumValue { name: "Pulsar", value: "PSR" },
];

const COSTELLAZIONI: &[EnumValue] = &[
    EnumValue { name: "Sconosciuta", value: "Sconosciuta" },
    EnumValue { name: "Andromeda", value: "And" },
    EnumValue { name: "Macchina Pneumatica", value: "Ant" },
    EnumValue { name: "Uccello del Paradiso", value: "Aps" },
    EnumValue { name: "Aquila", value: "Aql" },
    EnumValue { name: "Acquario", value: "Aqr" },
    EnumValue { name: "Altare", value: "Ara" },
    EnumValue { name: "Ariete", value: "Ari" },
    EnumValue { name: "Auriga", value: "Aur" },
    EnumValue { name: "Boote", value: "Boo" },
    EnumValue { name: "Bulino", value: "Cae" },
    EnumValue { name: "Giraffa", value: "Cam" },
    EnumValue { name: "Capricorno", value: "Cap" },
    EnumValue { name: "Carena", value: "Car" },
    EnumValue { name: "Cassiopea", value: "Cas" },
    EnumValue { name: "Centauro", value: "Cen" },
    EnumValue { name: "Cefeo", value: "Cep" },
    EnumValue { name: "Balena", value: "Cet" },
    EnumValue { name: "Camaleonte", value: "Cha" },
    EnumValue { name: "Compasso", value: "Cir" },
    EnumValue { name: "Cane Maggiore", value: "CMa" },
    EnumValue { name: "Cane Minore", value: "CMi" },
    EnumValue { name: "Cancro", value: "Cnc" },
    EnumValue { name: "Colomba", value: "Col" },
    EnumValue { name: "Chioma di Berenice", value: "Com" },
    EnumValue { name: "Corona Australe", value: "CrA" },
    EnumValue { name: "Corona Boreale", value: "CrB" },
    EnumValue { name: "Cratere", value: "Crt" },
    EnumValue { name: "Croce del Sud", value: "Cru" },
    EnumValue { name: "Corvo", value: "Crv" },
    EnumValue { name: "Cani da Caccia", value: "CVn" },
    EnumValue { name: "Cigno", value: "Cyg" },
    EnumValue { name: "Delfino", value: "Del" },
    EnumValue { name: "Dorado", value: "Dor" },
    EnumValue { name: "Dragone", value: "Dra" },
    EnumValue { name: "Cavallino", value: "Equ" },
    EnumValue { name: "Eridano", value: "Eri" },
    EnumValue { name: "Fornace", value: "For" },
    EnumValue { name: "Gemelli", value: "Gem" },
    EnumValue { name: "Gru", value: "Gru" },
    EnumValue { name: "Ercole", value: "Her" },
    EnumValue { name: "Orologio", value: "Hor" },
    EnumValue { name: "Idra Femmina", value: "Hya" },
    EnumValue { name: "Idra Maschio", value: "Hyi" },
    EnumValue { name: "Indiano", value: "Ind" },
    EnumValue { name: "Lucertola", value: "Lac" },
    EnumValue { name: "Leone", value: "Leo" },
    EnumValue { name: "Lepre", value: "Lep" },
    EnumValue { name: "Bilancia", value: "Lib" },
    EnumValue { name: "Leone Minore", value: "LMi" },
    EnumValue { name: "Lupo", value: "Lup" },
    EnumValue { name: "Lince", value: "Lyn" },
    EnumValue { name: "Lira", value: "Lyr" },
    EnumValue { name: "Mensa", value: "Men" },
    EnumValue { name: "Microscopio", value: "Mic" },
    EnumValue { name: "Unicorno", value: "Mon" },
    EnumValue { name: "Mosca", value: "Mus" },
    EnumValue { name: "Regolo", value: "Nor" },
    EnumValue { name: "Ottante", value: "Oct" },
    EnumValue { name: "Ofiuco", value: "Oph" },
    EnumValue { name: "Orione", value: "Ori" },
    EnumValue { name: "Pavone", value: "Pav" },
    EnumValue { name: "Pegaso", value: "Peg" },
    EnumValue { name: "Perseo", value: "Per" },
    EnumValue { name: "Fenice", value: "Phe" },
    EnumValue { name: "Pittore", value: "Pic" },
    EnumValue { name: "Pesce Australe", value: "PsA" },
    EnumValue { name: "Pesci", value: "Psc" },
    EnumValue { name: "Poppa", value: "Pup" },
    EnumValue { name: "Bussola", value: "Pyx" },
    EnumValue { name: "Reticolo", value: "Ret" },
    EnumValue { name: "Scultore", value: "Scl" },
    EnumValue { name: "Scorpione", value: "Sco" },
    EnumValue { name: "Scudo", value: "Sct" },
    EnumValue { name: "Serpente", value: "Ser" },
    EnumValue { name: "Sestante", value: "Sex" },
    EnumValue { name: "Freccia", value: "Sge" },
    EnumValue { name: "Sagittario", value: "Sgr" },
    EnumValue { name: "Toro", value: "Tau" },
    EnumValue { name: "Telescopio", value: "Tel" },
    EnumValue { name: "Triangolo Australe", value: "TrA" },
    EnumValue { name: "Triangolo", value: "Tri" },
    EnumValue { name: "Tucano", value: "Tuc" },
    EnumValue { name: "Orsa Maggiore", value: "UMa" },
    EnumValue { name: "Orsa Minore", value: "UMi" },
    EnumValue { name: "Vele", value: "Vel" },
    EnumValue { name: "Vergine", value: "Vir" },
    EnumValue { name: "Pesce Volante", value: "Vol" },
    EnumValue { name: "Volpetta", value: "Vul" },
];

const TIMEZONES: &[EnumValue] = &[
    EnumValue { name: "Africa/Abidjan", value: "Africa/Abidjan" },
    EnumValue { name: "Africa/Accra", value: "Africa/Accra" },
    EnumValue { name: "Africa/Addis_Ababa", value: "Africa/Addis_Ababa" },
    EnumValue { name: "Africa/Algiers", value: "Africa/Algiers" },
    EnumValue { name: "Africa/Asmara", value: "Africa/Asmara" },
    EnumValue { name: "Africa/Bamako", value: "Africa/Bamako" },
    EnumValue { name: "Africa/Bangui", value: "Africa/Bangui" },
    EnumValue { name: "Africa/Banjul", value: "Africa/Banjul" },
    EnumValue { name: "Africa/Bissau", value: "Africa/Bissau" },
    EnumValue { name: "Africa/Blantyre", value: "Africa/Blantyre" },
    EnumValue { name: "Africa/Brazzaville", value: "Africa/Brazzaville" },
    EnumValue { name: "Africa/Bujumbura", value: "Africa/Bujumbura" },
    EnumValue { name: "Africa/Cairo", value: "Africa/Cairo" },
    EnumValue { name: "Africa/Casablanca", value: "Africa/Casablanca" },
    EnumValue { name: "Africa/Ceuta", value: "Africa/Ceuta" },
    EnumValue { name: "Africa/Conakry", value: "Africa/Conakry" },
    EnumValue { name: "Africa/Dakar", value: "Africa/Dakar" },
    EnumValue { name: "Africa/Dar_es_Salaam", value: "Africa/Dar_es_Salaam" },
    EnumValue { name: "Africa/Djibouti", value: "Africa/Djibouti" },
    EnumValue { name: "Africa/Douala", value: "Africa/Douala" },
    EnumValue { name: "Africa/El_Aaiun", value: "Africa/El_Aaiun" },
    EnumValue { name: "Africa/Freetown", value: "Africa/Freetown" },
    EnumValue { name: "Africa/Gaborone", value: "Africa/Gaborone" },
    EnumValue { name: "Africa/Harare", value: "Africa/Harare" },
    EnumValue { name: "Africa/Johannesburg", value: "Africa/Johannesburg" },
    EnumValue { name: "Africa/Juba", value: "Africa/Juba" },
    EnumValue { name: "Africa/Kampala", value: "Africa/Kampala" },
    EnumValue { name: "Africa/Khartoum", value: "Africa/Khartoum" },
    EnumValue { name: "Africa/Kigali", value: "Africa/Kigali" },
    EnumValue { name: "Africa/Kinshasa", value: "Africa/Kinshasa" },
    EnumValue { name: "Africa/Lagos", value: "Africa/Lagos" },
    EnumValue { name: "Africa/Libreville", value: "Africa/Libreville" },
    EnumValue { name: "Africa/Lome", value: "Africa/Lome" },
    EnumValue { name: "Africa/Luanda", value: "Africa/Luanda" },
    EnumValue { name: "Africa/Lubumbashi", value: "Africa/Lubumbashi" },
    EnumValue { name: "Africa/Lusaka", value: "Africa/Lusaka" },
    EnumValue { name: "Africa/Malabo", value: "Africa/Malabo" },
    EnumValue { name: "Africa/Maputo", value: "Africa/Maputo" },
    EnumValue { name: "Africa/Maseru", value: "Africa/Maseru" },
    EnumValue { name: "Africa/Mbabane", value: "Africa/Mbabane" },
    EnumValue { name: "Africa/Mogadishu", value: "Africa/Mogadishu" },
    EnumValue { name: "Africa/Monrovia", value: "Africa/Monrovia" },
    EnumValue { name: "Africa/Nairobi", value: "Africa/Nairobi" },
    EnumValue { name: "Africa/Ndjamena", value: "Africa/Ndjamena" },
    EnumValue { name: "Africa/Niamey", value: "Africa/Niamey" },
    EnumValue { name: "Africa/Nouakchott", value: "Africa/Nouakchott" },
    EnumValue { name: "Africa/Ouagadougou", value: "Africa/Ouagadougou" },
    EnumValue { name: "Africa/Porto-Novo", value: "Africa/Porto-Novo" },
    EnumValue { name: "Africa/Sao_Tome", value: "Africa/Sao_Tome" },
    EnumValue { name: "Africa/Tripoli", value: "Africa/Tripoli" },
    EnumValue { name: "Africa/Tunis", value: "Africa/Tunis" },
    EnumValue { name: "Africa/Windhoek", value: "Africa/Windhoek" },
    EnumValue { name: "America/Adak", value: "America/Adak" },
    EnumValue { name: "America/Anchorage", value: "America/Anchorage" },
    EnumValue { name: "America/Anguilla", value: "America/Anguilla" },
    EnumValue { name: "America/Antigua", value: "America/Antigua" },
    EnumValue { name: "America/Araguaina", value: "America/Araguaina" },
    EnumValue { name: "America/Argentina/Buenos_Aires", value: "America/Argentina/Buenos_Aires" },
    EnumValue { name: "America/Argentina/Catamarca", value: "America/Argentina/Catamarca" },
    EnumValue { name: "America/Argentina/Cordoba", value: "America/Argentina/Cordoba" },
    EnumValue { name: "America/Argentina/Jujuy", value: "America/Argentina/Jujuy" },
    EnumValue { name: "America/Argentina/La_Rioja", value: "America/Argentina/La_Rioja" },
    EnumValue { name: "America/Argentina/Mendoza", value: "America/Argentina/Mendoza" },
    EnumValue { name: "America/Argentina/Rio_Gallegos", value: "America/Argentina/Rio_Gallegos" },
    EnumValue { name: "America/Argentina/Salta", value: "America/Argentina/Salta" },
    EnumValue { name: "America/Argentina/San_Juan", value: "America/Argentina/San_Juan" },
    EnumValue { name: "America/Argentina/San_Luis", value: "America/Argentina/San_Luis" },
    EnumValue { name: "America/Argentina/Tucuman", value: "America/Argentina/Tucuman" },
    EnumValue { name: "America/Argentina/Ushuaia", value: "America/Argentina/Ushuaia" },
    EnumValue { name: "America/Aruba", value: "America/Aruba" },
    EnumValue { name: "America/Asuncion", value: "America/Asuncion" },
    EnumValue { name: "America/Atikokan", value: "America/Atikokan" },
    EnumValue { name: "America/Bahia", value: "America/Bahia" },
    EnumValue { name: "America/Bahia_Banderas", value: "America/Bahia_Banderas" },
    EnumValue { name: "America/Barbados", value: "America/Barbados" },
    EnumValue { name: "America/Belem", value: "America/Belem" },
    EnumValue { name: "America/Belize", value: "America/Belize" },
    EnumValue { name: "America/Blanc-Sablon", value: "America/Blanc-Sablon" },
    EnumValue { name: "America/Boa_Vista", value: "America/Boa_Vista" },
    EnumValue { name: "America/Bogota", value: "America/Bogota" },
    EnumValue { name: "America/Boise", value: "America/Boise" },
    EnumValue { name: "America/Cambridge_Bay", value: "America/Cambridge_Bay" },
    EnumValue { name: "America/Campo_Grande", value: "America/Campo_Grande" },
    EnumValue { name: "America/Cancun", value: "America/Cancun" },
    EnumValue { name: "America/Caracas", value: "America/Caracas" },
    EnumValue { name: "America/Cayenne", value: "America/Cayenne" },
    EnumValue { name: "America/Cayman", value: "America/Cayman" },
    EnumValue { name: "America/Chicago", value: "America/Chicago" },
    EnumValue { name: "America/Chihuahua", value: "America/Chihuahua" },
    EnumValue { name: "America/Costa_Rica", value: "America/Costa_Rica" },
    EnumValue { name: "America/Creston", value: "America/Creston" },
    EnumValue { name: "America/Cuiaba", value: "America/Cuiaba" },
    EnumValue { name: "America/Curacao", value: "America/Curacao" },
    EnumValue { name: "America/Danmarkshavn", value: "America/Danmarkshavn" },
    EnumValue { name: "America/Dawson", value: "America/Dawson" },
    EnumValue { name: "America/Dawson_Creek", value: "America/Dawson_Creek" },
    EnumValue { name: "America/Denver", value: "America/Denver" },
    EnumValue { name: "America/Detroit", value: "America/Detroit" },
    EnumValue { name: "America/Dominica", value: "America/Dominica" },
    EnumValue { name: "America/Edmonton", value: "America/Edmonton" },
    EnumValue { name: "America/Eirunepe", value: "America/Eirunepe" },
    EnumValue { name: "America/El_Salvador", value: "America/El_Salvador" },
    EnumValue { name: "America/Fort_Nelson", value: "America/Fort_Nelson" },
    EnumValue { name: "America/Fortaleza", value: "America/Fortaleza" },
    EnumValue { name: "America/Glace_Bay", value: "America/Glace_Bay" },
    EnumValue { name: "America/Godthab", value: "America/Godthab" },
    EnumValue { name: "America/Goose_Bay", value: "America/Goose_Bay" },
    EnumValue { name: "America/Grand_Turk", value: "America/Grand_Turk" },
    EnumValue { name: "America/Grenada", value: "America/Grenada" },
    EnumValue { name: "America/Guadeloupe", value: "America/Guadeloupe" },
    EnumValue { name: "America/Guatemala", value: "America/Guatemala" },
    EnumValue { name: "America/Guayaquil", value: "America/Guayaquil" },
    EnumValue { name: "America/Guyana", value: "America/Guyana" },
    EnumValue { name: "America/Halifax", value: "America/Halifax" },
    EnumValue { name: "America/Havana", value: "America/Havana" },
    EnumValue { name: "America/Hermosillo", value: "America/Hermosillo" },
    EnumValue { name: "America/Indiana/Indianapolis", value: "America/Indiana/Indianapolis" },
    EnumValue { name: "America/Indiana/Knox", value: "America/Indiana/Knox" },
    EnumValue { name: "America/Indiana/Marengo", value: "America/Indiana/Marengo" },
    EnumValue { name: "America/Indiana/Petersburg", value: "America/Indiana/Petersburg" },
    EnumValue { name: "America/Indiana/Tell_City", value: "America/Indiana/Tell_City" },
    EnumValue { name: "America/Indiana/Vevay", value: "America/Indiana/Vevay" },
    EnumValue { name: "America/Indiana/Vincennes", value: "America/Indiana/Vincennes" },
    EnumValue { name: "America/Indiana/Winamac", value: "America/Indiana/Winamac" },
    EnumValue { name: "America/Inuvik", value: "America/Inuvik" },
    EnumValue { name: "America/Iqaluit", value: "America/Iqaluit" },
    EnumValue { name: "America/Jamaica", value: "America/Jamaica" },
    EnumValue { name: "America/Juneau", value: "America/Juneau" },
    EnumValue { name: "America/Kentucky/Louisville", value: "America/Kentucky/Louisville" },
    EnumValue { name: "America/Kentucky/Monticello", value: "America/Kentucky/Monticello" },
    EnumValue { name: "America/Kralendijk", value: "America/Kralendijk" },
    EnumValue { name: "America/La_Paz", value: "America/La_Paz" },
    EnumValue { name: "America/Lima", value: "America/Lima" },
    EnumValue { name: "America/Los_Angeles", value: "America/Los_Angeles" },
    EnumValue { name: "America/Lower_Princes", value: "America/Lower_Princes" },
    EnumValue { name: "America/Maceio", value: "America/Maceio" },
    EnumValue { name: "America/Managua", value: "America/Managua" },
    EnumValue { name: "America/Manaus", value: "America/Manaus" },
    EnumValue { name: "America/Marigot", value: "America/Marigot" },
    EnumValue { name: "America/Martinique", value: "America/Martinique" },
    EnumValue { name: "America/Matamoros", value: "America/Matamoros" },
    EnumValue { name: "America/Mazatlan", value: "America/Mazatlan" },
    EnumValue { name: "America/Menominee", value: "America/Menominee" },
    EnumValue { name: "America/Merida", value: "America/Merida" },
    EnumValue { name: "America/Metlakatla", value: "America/Metlakatla" },
    EnumValue { name: "America/Mexico_City", value: "America/Mexico_City" },
    EnumValue { name: "America/Miquelon", value: "America/Miquelon" },
    EnumValue { name: "America/Moncton", value: "America/Moncton" },
    EnumValue { name: "America/Monterrey", value: "America/Monterrey" },
    EnumValue { name: "America/Montevideo", value: "America/Montevideo" },
    EnumValue { name: "America/Montserrat", value: "America/Montserrat" },
    EnumValue { name: "America/Nassau", value: "America/Nassau" },
    EnumValue { name: "America/New_York", value: "America/New_York" },
    EnumValue { name: "America/Nipigon", value: "America/Nipigon" },
    EnumValue { name: "America/Nome", value: "America/Nome" },
    EnumValue { name: "America/Noronha", value: "America/Noronha" },
    EnumValue { name: "America/North_Dakota/Beulah", value: "America/North_Dakota/Beulah" },
    EnumValue { name: "America/North_Dakota/Center", value: "America/North_Dakota/Center" },
    EnumValue { name: "America/North_Dakota/New_Salem", value: "America/North_Dakota/New_Salem" },
    EnumValue { name: "America/Nuuk", value: "America/Nuuk" },
    EnumValue { name: "America/Ojinaga", value: "America/Ojinaga" },
    EnumValue { name: "America/Panama", value: "America/Panama" },
    EnumValue { name: "America/Pangnirtung", value: "America/Pangnirtung" },
    EnumValue { name: "America/Paramaribo", value: "America/Paramaribo" },
    EnumValue { name: "America/Phoenix", value: "America/Phoenix" },
    EnumValue { name: "America/Port-au-Prince", value: "America/Port-au-Prince" },
    EnumValue { name: "America/Port_of_Spain", value: "America/Port_of_Spain" },
    EnumValue { name: "America/Porto_Velho", value: "America/Porto_Velho" },
    EnumValue { name: "America/Puerto_Rico", value: "America/Puerto_Rico" },
    EnumValue { name: "America/Punta_Arenas", value: "America/Punta_Arenas" },
    EnumValue { name: "America/Rainy_River", value: "America/Rainy_River" },
    EnumValue { name: "America/Rankin_Inlet", value: "America/Rankin_Inlet" },
    EnumValue { name: "America/Recife", value: "America/Recife" },
    EnumValue { name: "America/Regina", value: "America/Regina" },
    EnumValue { name: "America/Resolute", value: "America/Resolute" },
    EnumValue { name: "America/Rio_Branco", value: "America/Rio_Branco" },
    EnumValue { name: "America/Santarem", value: "America/Santarem" },
    EnumValue { name: "America/Santiago", value: "America/Santiago" },
    EnumValue { name: "America/Santo_Domingo", value: "America/Santo_Domingo" },
    EnumValue { name: "America/Sao_Paulo", value: "America/Sao_Paulo" },
    EnumValue { name: "America/Scoresbysund", value: "America/Scoresbysund" },
    EnumValue { name: "America/Sitka", value: "America/Sitka" },
    EnumValue { name: "America/St_Barthelemy", value: "America/St_Barthelemy" },
    EnumValue { name: "America/St_Johns", value: "America/St_Johns" },
    EnumValue { name: "America/St_Kitts", value: "America/St_Kitts" },
    EnumValue { name: "America/St_Lucia", value: "America/St_Lucia" },
    EnumValue { name: "America/St_Thomas", value: "America/St_Thomas" },
    EnumValue { name: "America/St_Vincent", value: "America/St_Vincent" },
    EnumValue { name: "America/Swift_Current", value: "America/Swift_Current" },
    EnumValue { name: "America/Tegucigalpa", value: "America/Tegucigalpa" },
    EnumValue { name: "America/Thule", value: "America/Thule" },
    EnumValue { name: "America/Thunder_Bay", value: "America/Thunder_Bay" },
    EnumValue { name: "America/Tijuana", value: "America/Tijuana" },
    EnumValue { name: "America/Toronto", value: "America/Toronto" },
    EnumValue { name: "America/Tortola", value: "America/Tortola" },
    EnumValue { name: "America/Vancouver", value: "America/Vancouver" },
    EnumValue { name: "America/Whitehorse", value: "America/Whitehorse" },
    EnumValue { name: "America/Winnipeg", value: "America/Winnipeg" },
    EnumValue { name: "America/Yakutat", value: "America/Yakutat" },
    EnumValue { name: "America/Yellowknife", value: "America/Yellowknife" },
    EnumValue { name: "Antarctica/Casey", value: "Antarctica/Casey" },
    EnumValue { name: "Antarctica/Davis", value: "Antarctica/Davis" },
    EnumValue { name: "Antarctica/DumontDUrville", value: "Antarctica/DumontDUrville" },
    EnumValue { name: "Antarctica/Macquarie", value: "Antarctica/Macquarie" },
    EnumValue { name: "Antarctica/Mawson", value: "Antarctica/Mawson" },
    EnumValue { name: "Antarctica/McMurdo", value: "Antarctica/McMurdo" },
    EnumValue { name: "Antarctica/Palmer", value: "Antarctica/Palmer" },
    EnumValue { name: "Antarctica/Rothera", value: "Antarctica/Rothera" },
    EnumValue { name: "Antarctica/Syowa", value: "Antarctica/Syowa" },
    EnumValue { name: "Antarctica/Troll", value: "Antarctica/Troll" },
    EnumValue { name: "Antarctica/Vostok", value: "Antarctica/Vostok" },
    EnumValue { name: "Asia/Aden", value: "Asia/Aden" },
    EnumValue { name: "Asia/Almaty", value: "Asia/Almaty" },
    EnumValue { name: "Asia/Amman", value: "Asia/Amman" },
    EnumValue { name: "Asia/Anadyr", value: "Asia/Anadyr" },
    EnumValue { name: "Asia/Aqtau", value: "Asia/Aqtau" },
    EnumValue { name: "Asia/Aqtobe", value: "Asia/Aqtobe" },
    EnumValue { name: "Asia/Ashgabat", value: "Asia/Ashgabat" },
    EnumValue { name: "Asia/Atyrau", value: "Asia/Atyrau" },
    EnumValue { name: "Asia/Baghdad", value: "Asia/Baghdad" },
    EnumValue { name: "Asia/Bahrain", value: "Asia/Bahrain" },
    EnumValue { name: "Asia/Baku", value: "Asia/Baku" },
    EnumValue { name: "Asia/Bangkok", value: "Asia/Bangkok" },
    EnumValue { name: "Asia/Barnaul", value: "Asia/Barnaul" },
    EnumValue { name: "Asia/Beirut", value: "Asia/Beirut" },
    EnumValue { name: "Asia/Bishkek", value: "Asia/Bishkek" },
    EnumValue { name: "Asia/Brunei", value: "Asia/Brunei" },
    EnumValue { name: "Asia/Chita", value: "Asia/Chita" },
    EnumValue { name: "Asia/Choibalsan", value: "Asia/Choibalsan" },
    EnumValue { name: "Asia/Colombo", value: "Asia/Colombo" },
    EnumValue { name: "Asia/Damascus", value: "Asia/Damascus" },
    EnumValue { name: "Asia/Dhaka", value: "Asia/Dhaka" },
    EnumValue { name: "Asia/Dili", value: "Asia/Dili" },
    EnumValue { name: "Asia/Dubai", value: "Asia/Dubai" },
    EnumValue { name: "Asia/Dushanbe", value: "Asia/Dushanbe" },
    EnumValue { name: "Asia/Famagusta", value: "Asia/Famagusta" },
    EnumValue { name: "Asia/Gaza", value: "Asia/Gaza" },
    EnumValue { name: "Asia/Hebron", value: "Asia/Hebron" },
    EnumValue { name: "Asia/Ho_Chi_Minh", value: "Asia/Ho_Chi_Minh" },
    EnumValue { name: "Asia/Hong_Kong", value: "Asia/Hong_Kong" },
    EnumValue { name: "Asia/Hovd", value: "Asia/Hovd" },
    EnumValue { name: "Asia/Irkutsk", value: "Asia/Irkutsk" },
    EnumValue { name: "Asia/Jakarta", value: "Asia/Jakarta" },
    EnumValue { name: "Asia/Jayapura", value: "Asia/Jayapura" },
    EnumValue { name: "Asia/Jerusalem", value: "Asia/Jerusalem" },
    EnumValue { name: "Asia/Kabul", value: "Asia/Kabul" },
    EnumValue { name: "Asia/Kamchatka", value: "Asia/Kamchatka" },
    EnumValue { name: "Asia/Karachi", value: "Asia/Karachi" },
    EnumValue { name: "Asia/Kathmandu", value: "Asia/Kathmandu" },
    EnumValue { name: "Asia/Khandyga", value: "Asia/Khandyga" },
    EnumValue { name: "Asia/Kolkata", value: "Asia/Kolkata" },
    EnumValue { name: "Asia/Krasnoyarsk", value: "Asia/Krasnoyarsk" },
    EnumValue { name: "Asia/Kuala_Lumpur", value: "Asia/Kuala_Lumpur" },
    EnumValue { name: "Asia/Kuching", value: "Asia/Kuching" },
    EnumValue { name: "Asia/Kuwait", value: "Asia/Kuwait" },
    EnumValue { name: "Asia/Macau", value: "Asia/Macau" },
    EnumValue { name: "Asia/Magadan", value: "Asia/Magadan" },
    EnumValue { name: "Asia/Makassar", value: "Asia/Makassar" },
    EnumValue { name: "Asia/Manila", value: "Asia/Manila" },
    EnumValue { name: "Asia/Muscat", value: "Asia/Muscat" },
    EnumValue { name: "Asia/Nicosia", value: "Asia/Nicosia" },
    EnumValue { name: "Asia/Novokuznetsk", value: "Asia/Novokuznetsk" },
    EnumValue { name: "Asia/Novosibirsk", value: "Asia/Novosibirsk" },
    EnumValue { name: "Asia/Omsk", value: "Asia/Omsk" },
    EnumValue { name: "Asia/Oral", value: "Asia/Oral" },
    EnumValue { name: "Asia/Phnom_Penh", value: "Asia/Phnom_Penh" },
    EnumValue { name: "Asia/Pontianak", value: "Asia/Pontianak" },
    EnumValue { name: "Asia/Pyongyang", value: "Asia/Pyongyang" },
    EnumValue { name: "Asia/Qatar", value: "Asia/Qatar" },
    EnumValue { name: "Asia/Qostanay", value: "Asia/Qostanay" },
    EnumValue { name: "Asia/Qyzylorda", value: "Asia/Qyzylorda" },
    EnumValue { name: "Asia/Riyadh", value: "Asia/Riyadh" },
    EnumValue { name: "Asia/Sakhalin", value: "Asia/Sakhalin" },
    EnumValue { name: "Asia/Samarkand", value: "Asia/Samarkand" },
    EnumValue { name: "Asia/Seoul", value: "Asia/Seoul" },
    EnumValue { name: "Asia/Shanghai", value: "Asia/Shanghai" },
    EnumValue { name: "Asia/Singapore", value: "Asia/Singapore" },
    EnumValue { name: "Asia/Srednekolymsk", value: "Asia/Srednekolymsk" },
    EnumValue { name: "Asia/Taipei", value: "Asia/Taipei" },
    EnumValue { name: "Asia/Tashkent", value: "Asia/Tashkent" },
    EnumValue { name: "Asia/Tbilisi", value: "Asia/Tbilisi" },
    EnumValue { name: "Asia/Tehran", value: "Asia/Tehran" },
    EnumValue { name: "Asia/Thimphu", value: "Asia/Thimphu" },
    EnumValue { name: "Asia/Tokyo", value: "Asia/Tokyo" },
    EnumValue { name: "Asia/Tomsk", value: "Asia/Tomsk" },
    EnumValue { name: "Asia/Ulaanbaatar", value: "Asia/Ulaanbaatar" },
    EnumValue { name: "Asia/Urumqi", value: "Asia/Urumqi" },
    EnumValue { name: "Asia/Ust-Nera", value: "Asia/Ust-Nera" },
    EnumValue { name: "Asia/Vientiane", value: "Asia/Vientiane" },
    EnumValue { name: "Asia/Vladivostok", value: "Asia/Vladivostok" },
    EnumValue { name: "Asia/Yakutsk", value: "Asia/Yakutsk" },
    EnumValue { name: "Asia/Yangon", value: "Asia/Yangon" },
    EnumValue { name: "Asia/Yekaterinburg", value: "Asia/Yekaterinburg" },
    EnumValue { name: "Asia/Yerevan", value: "Asia/Yerevan" },
    EnumValue { name: "Atlantic/Azores", value: "Atlantic/Azores" },
    EnumValue { name: "Atlantic/Bermuda", value: "Atlantic/Bermuda" },
    EnumValue { name: "Atlantic/Canary", value: "Atlantic/Canary" },
    EnumValue { name: "Atlantic/Cape_Verde", value: "Atlantic/Cape_Verde" },
    EnumValue { name: "Atlantic/Faroe", value: "Atlantic/Faroe" },
    EnumValue { name: "Atlantic/Madeira", value: "Atlantic/Madeira" },
    EnumValue { name: "Atlantic/Reykjavik", value: "Atlantic/Reykjavik" },
    EnumValue { name: "Atlantic/South_Georgia", value: "Atlantic/South_Georgia" },
    EnumValue { name: "Atlantic/St_Helena", value: "Atlantic/St_Helena" },
    EnumValue { name: "Atlantic/Stanley", value: "Atlantic/Stanley" },
    EnumValue { name: "Australia/Adelaide", value: "Australia/Adelaide" },
    EnumValue { name: "Australia/Brisbane", value: "Australia/Brisbane" },
    EnumValue { name: "Australia/Broken_Hill", value: "Australia/Broken_Hill" },
    EnumValue { name: "Australia/Darwin", value: "Australia/Darwin" },
    EnumValue { name: "Australia/Eucla", value: "Australia/Eucla" },
    EnumValue { name: "Australia/Hobart", value: "Australia/Hobart" },
    EnumValue { name: "Australia/Lindeman", value: "Australia/Lindeman" },
    EnumValue { name: "Australia/Lord_Howe", value: "Australia/Lord_Howe" },
    EnumValue { name: "Australia/Melbourne", value: "Australia/Melbourne" },
    EnumValue { name: "Australia/Perth", value: "Australia/Perth" },
    EnumValue { name: "Australia/Sydney", value: "Australia/Sydney" },
    EnumValue { name: "Europe/Amsterdam", value: "Europe/Amsterdam" },
    EnumValue { name: "Europe/Andorra", value: "Europe/Andorra" },
    EnumValue { name: "Europe/Astrakhan", value: "Europe/Astrakhan" },
    EnumValue { name: "Europe/Athens", value: "Europe/Athens" },
    EnumValue { name: "Europe/Belgrade", value: "Europe/Belgrade" },
    EnumValue { name: "Europe/Berlin", value: "Europe/Berlin" },
    EnumValue { name: "Europe/Bratislava", value: "Europe/Bratislava" },
    EnumValue { name: "Europe/Brussels", value: "Europe/Brussels" },
    EnumValue { name: "Europe/Bucharest", value: "Europe/Bucharest" },
    EnumValue { name: "Europe/Budapest", value: "Europe/Budapest" },
    EnumValue { name: "Europe/Busingen", value: "Europe/Busingen" },
    EnumValue { name: "Europe/Chisinau", value: "Europe/Chisinau" },
    EnumValue { name: "Europe/Copenhagen", value: "Europe/Copenhagen" },
    EnumValue { name: "Europe/Dublin", value: "Europe/Dublin" },
    EnumValue { name: "Europe/Gibraltar", value: "Europe/Gibraltar" },
    EnumValue { name: "Europe/Guernsey", value: "Europe/Guernsey" },
    EnumValue { name: "Europe/Helsinki", value: "Europe/Helsinki" },
    EnumValue { name: "Europe/Isle_of_Man", value: "Europe/Isle_of_Man" },
    EnumValue { name: "Europe/Istanbul", value: "Europe/Istanbul" },
    EnumValue { name: "Europe/Jersey", value: "Europe/Jersey" },
    EnumValue { name: "Europe/Kaliningrad", value: "Europe/Kaliningrad" },
    EnumValue { name: "Europe/Kiev", value: "Europe/Kiev" },
    EnumValue { name: "Europe/Kirov", value: "Europe/Kirov" },
    EnumValue { name: "Europe/Lisbon", value: "Europe/Lisbon" },
    EnumValue { name: "Europe/Ljubljana", value: "Europe/Ljubljana" },
    EnumValue { name: "Europe/London", value: "Europe/London" },
    EnumValue { name: "Europe/Luxembourg", value: "Europe/Luxembourg" },
    EnumValue { name: "Europe/Madrid", value: "Europe/Madrid" },
    EnumValue { name: "Europe/Malta", value: "Europe/Malta" },
    EnumValue { name: "Europe/Mariehamn", value: "Europe/Mariehamn" },
    EnumValue { name: "Europe/Minsk", value: "Europe/Minsk" },
    EnumValue { name: "Europe/Monaco", value: "Europe/Monaco" },
    EnumValue { name: "Europe/Moscow", value: "Europe/Moscow" },
    EnumValue { name: "Europe/Oslo", value: "Europe/Oslo" },
    EnumValue { name: "Europe/Paris", value: "Europe/Paris" },
    EnumValue { name: "Europe/Podgorica", value: "Europe/Podgorica" },
    EnumValue { name: "Europe/Prague", value: "Europe/Prague" },
    EnumValue { name: "Europe/Riga", value: "Europe/Riga" },
    EnumValue { name: "Europe/Rome", value: "Europe/Rome" },
    EnumValue { name: "Europe/Samara", value: "Europe/Samara" },
    EnumValue { name: "Europe/San_Marino", value: "Europe/San_Marino" },
    EnumValue { name: "Europe/Sarajevo", value: "Europe/Sarajevo" },
    EnumValue { name: "Europe/Saratov", value: "Europe/Saratov" },
    EnumValue { name: "Europe/Simferopol", value: "Europe/Simferopol" },
    EnumValue { name: "Europe/Skopje", value: "Europe/Skopje" },
    EnumValue { name: "Europe/Sofia", value: "Europe/Sofia" },
    EnumValue { name: "Europe/Stockholm", value: "Europe/Stockholm" },
    EnumValue { name: "Europe/Tallinn", value: "Europe/Tallinn" },
    EnumValue { name: "Europe/Tirane", value: "Europe/Tirane" },
    EnumValue { name: "Europe/Ulyanovsk", value: "Europe/Ulyanovsk" },
    EnumValue { name: "Europe/Uzhgorod", value: "Europe/Uzhgorod" },
    EnumValue { name: "Europe/Vaduz", value: "Europe/Vaduz" },
    EnumValue { name: "Europe/Vatican", value: "Europe/Vatican" },
    EnumValue { name: "Europe/Vienna", value: "Europe/Vienna" },
    EnumValue { name: "Europe/Vilnius", value: "Europe/Vilnius" },
    EnumValue { name: "Europe/Volgograd", value: "Europe/Volgograd" },
    EnumValue { name: "Europe/Warsaw", value: "Europe/Warsaw" },
    EnumValue { name: "Europe/Zagreb", value: "Europe/Zagreb" },
    EnumValue { name: "Europe/Zaporozhye", value: "Europe/Zaporozhye" },
    EnumValue { name: "Europe/Zurich", value: "Europe/Zurich" },
    EnumValue { name: "Indian/Antananarivo", value: "Indian/Antananarivo" },
    EnumValue { name: "Indian/Chagos", value: "Indian/Chagos" },
    EnumValue { name: "Indian/Christmas", value: "Indian/Christmas" },
    EnumValue { name: "Indian/Cocos", value: "Indian/Cocos" },
    EnumValue { name: "Indian/Comoro", value: "Indian/Comoro" },
    EnumValue { name: "Indian/Kerguelen", value: "Indian/Kerguelen" },
    EnumValue { name: "Indian/Mahe", value: "Indian/Mahe" },
    EnumValue { name: "Indian/Maldives", value: "Indian/Maldives" },
    EnumValue { name: "Indian/Mauritius", value: "Indian/Mauritius" },
    EnumValue { name: "Indian/Mayotte", value: "Indian/Mayotte" },
    EnumValue { name: "Indian/Reunion", value: "Indian/Reunion" },
    EnumValue { name: "Pacific/Apia", value: "Pacific/Apia" },
    EnumValue { name: "Pacific/Auckland", value: "Pacific/Auckland" },
    EnumValue { name: "Pacific/Bougainville", value: "Pacific/Bougainville" },
    EnumValue { name: "Pacific/Chatham", value: "Pacific/Chatham" },
    EnumValue { name: "Pacific/Chuuk", value: "Pacific/Chuuk" },
    EnumValue { name: "Pacific/Easter", value: "Pacific/Easter" },
    EnumValue { name: "Pacific/Efate", value: "Pacific/Efate" },
    EnumValue { name: "Pacific/Enderbury", value: "Pacific/Enderbury" },
    EnumValue { name: "Pacific/Fakaofo", value: "Pacific/Fakaofo" },
    EnumValue { name: "Pacific/Fiji", value: "Pacific/Fiji" },
    EnumValue { name: "Pacific/Funafuti", value: "Pacific/Funafuti" },
    EnumValue { name: "Pacific/Galapagos", value: "Pacific/Galapagos" },
    EnumValue { name: "Pacific/Gambier", value: "Pacific/Gambier" },
    EnumValue { name: "Pacific/Guadalcanal", value: "Pacific/Guadalcanal" },
    EnumValue { name: "Pacific/Guam", value: "Pacific/Guam" },
    EnumValue { name: "Pacific/Honolulu", value: "Pacific/Honolulu" },
    EnumValue { name: "Pacific/Kanton", value: "Pacific/Kanton" },
    EnumValue { name: "Pacific/Kiritimati", value: "Pacific/Kiritimati" },
    EnumValue { name: "Pacific/Kosrae", value: "Pacific/Kosrae" },
    EnumValue { name: "Pacific/Kwajalein", value: "Pacific/Kwajalein" },
    EnumValue { name: "Pacific/Majuro", value: "Pacific/Majuro" },
    EnumValue { name: "Pacific/Marquesas", value: "Pacific/Marquesas" },
    EnumValue { name: "Pacific/Midway", value: "Pacific/Midway" },
    EnumValue { name: "Pacific/Nauru", value: "Pacific/Nauru" },
    EnumValue { name: "Pacific/Niue", value: "Pacific/Niue" },
    EnumValue { name: "Pacific/Norfolk", value: "Pacific/Norfolk" },
    EnumValue { name: "Pacific/Noumea", value: "Pacific/Noumea" },
    EnumValue { name: "Pacific/Pago_Pago", value: "Pacific/Pago_Pago" },
    EnumValue { name: "Pacific/Palau", value: "Pacific/Palau" },
    EnumValue { name: "Pacific/Pitcairn", value: "Pacific/Pitcairn" },
    EnumValue { name: "Pacific/Pohnpei", value: "Pacific/Pohnpei" },
    EnumValue { name: "Pacific/Port_Moresby", value: "Pacific/Port_Moresby" },
    EnumValue { name: "Pacific/Rarotonga", value: "Pacific/Rarotonga" },
    EnumValue { name: "Pacific/Saipan", value: "Pacific/Saipan" },
    EnumValue { name: "Pacific/Tahiti", value: "Pacific/Tahiti" },
    EnumValue { name: "Pacific/Tarawa", value: "Pacific/Tarawa" },
    EnumValue { name: "Pacific/Tongatapu", value: "Pacific/Tongatapu" },
    EnumValue { name: "Pacific/Wake", value: "Pacific/Wake" },
    EnumValue { name: "Pacific/Wallis", value: "Pacific/Wallis" },
];

pub struct StaticsRepository;

impl StaticsRepository {
    pub fn new() -> Self {
        Self
    }

    pub fn get_tipi_strumentazione(&self) -> &'static [EnumValue] {
        TIPO_STRUMENTAZIONE
    }

    pub fn get_tipi_oggetto(&self) -> &'static [EnumValue] {
        TIPO_OGGETTO
    }

    pub fn get_costellazioni(&self) -> &'static [EnumValue] {
        COSTELLAZIONI
    }

    pub fn get_timezones(&self) -> &'static [EnumValue] {
        TIMEZONES
    }
}
