[package]
name = "app_managment"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
console = "0.16.0"
cornetti = { path = "../cornetti-rust/cornetti", features = ["mongo", "redisdb", "filemanager", "mail", "templates"] }
cornetti_macros = { path = "../cornetti-rust/cornetti_macros" }
tracing = "0.1"
app_modules = { path = "../app_modules"}
redis = { version = "1", features = ["tokio-comp"] }
tokio = "1.45.0"
log = "0.4.27"
env_logger = "0.11.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["rustls-tls", "blocking"], default-features = false }
bson = "3"
futures = "0.3"
validator = "0.20"
lettre = { version = "0.11.17", features = ["tokio1-native-tls"] }
minijinja = "2.11.0"
