[package]
name = "cornetti_macros"
version = "0.1.0"
edition = "2024"
authors = ["Valerio Faiuolo <valerio.faiuolo@errepinet.it>"]
description = "Cornetti macros framework"


[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
serde_json = "1"

[dev-dependencies]
cornetti = { path = "../cornetti" }
