use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

/// OAuth2 metadata associated with a local user.
/// Separate entity from the user — the consumer decides where to persist it (SQL, Mongo, etc.).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuth2Metadata {
    pub provider: String,
    pub provider_user_id: String,
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_at: Option<DateTime<Utc>>,
    pub scopes: Vec<String>,
    pub user_id: String,
    pub tenant_id: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// User data retrieved from the OAuth2 provider after the token exchange.
/// The `email`, `name`, `avatar_url` fields are Optional because not all providers
/// always return them (e.g. Apple may omit the email).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuth2UserTransportData {
    pub provider: String,
    pub provider_user_id: String,
    pub email: Option<String>,
    /// Email verification status **as declared by the provider**.
    ///
    /// `None` means *unknown*: the provider does not expose this data or
    /// verification was not possible. It must not be interpreted as `false`
    /// nor as `true`.
    ///
    /// # Security
    ///
    /// Automatically linking an existing local account by `email` is safe
    /// **only** when this field is `Some(true)`. With `None`, an attacker
    /// could register an email they do not own with the provider and gain
    /// access to the corresponding local account.
    pub email_verified: Option<bool>,
    pub name: Option<String>,
    pub avatar_url: Option<String>,
    /// Raw payload from the provider, for access to provider-specific fields.
    pub raw_data: serde_json::Value,
}

/// Callback request body for API/mobile mode.
#[derive(Debug, Deserialize)]
pub struct OAuth2CallbackRequest {
    pub code: String,
    pub state: String,
    /// PKCE verifier generated by the client.
    ///
    /// Required if the flow was started by providing a `code_challenge`
    /// (API/mobile mode). Must be absent when PKCE was generated by the
    /// server, otherwise the callback fails with `pkce_mode_mismatch`.
    #[serde(default)]
    pub code_verifier: Option<String>,
}

/// Data associated with a CSRF state in the OAuth2 store.
///
/// Serialized as JSON in the string value of `OAuth2SessionStore`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OAuth2StateData {
    /// PKCE verifier generated by the server.
    ///
    /// `None` when PKCE is managed by the client: in that case the verifier
    /// never leaves the device and must be provided in the callback.
    pub pkce_verifier: Option<String>,
}

/// Query string accepted by OAuth2 login handlers.
#[derive(Debug, Deserialize, ToSchema)]
pub struct OAuth2LoginQuery {
    /// PKCE code challenge (S256 method) generated by the client.
    ///
    /// Optional in the web flow (where the binding is guaranteed by the state
    /// cookie), required in API/mobile flow.
    pub code_challenge: Option<String>,
}

/// OAuth2 login response in API/mobile mode.
#[derive(Debug, Clone, Serialize, ToSchema)]
pub struct OAuth2LoginResponse {
    /// Authorization URL to open on the provider.
    pub auth_url: String,
    /// CSRF state to return in the callback.
    pub state: String,
}
