[package]
name = "app_gateway_main"
version = "0.1.0"
edition = "2024"
build = "build.rs"


[dependencies]
serde = { version = "1", features = ["derive"] }
chrono = { version ="0.4", features = ["serde"] }
mongodb = { version = "3" }
bson = { version = "2", features = ["chrono-0_4"] } # Needed for using chrono datetime in doc
cornetti = { path = "../cornetti-rust/cornetti", features = ["mongo", "auth", "actix", "actix-auth", "auth-oauth2", "actix-auth-oauth2", "redisdb", "filemanager" ] }
cornetti_macros = { path = "../cornetti-rust/cornetti_macros" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2"
app_modules = { path = "../app_modules" }
utoipa = { version ="5", features = ["actix_extras", "chrono"]}
utoipa-swagger-ui = { version = "9", features = ["actix-web"] }
actix-web = "4.11.0"
actix-multipart = "0.7.2"

[build-dependencies]
chrono = { version = "0.4", features = ["serde"] }
